name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

      - name: Build with MinGW
        shell: msys2 {0}
        run: |
          mingw32-make test-build

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            client.exe
            server.exe

